# steps:
# - name: 'docker'
#   args:

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild-docker-image:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/cloudbuild-docker-image:$SHORT_SHA']