# steps:
# - name: 'docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
# images:
# - 'gcr.io/$PROJECT_ID/gcpdevops'

# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild-docker-image:$SHORT_SHA', '.']
# images: ['gcr.io/$PROJECT_ID/cloudbuild-docker-image:$SHORT_SHA']

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/gcp-project/quickstart-image:tag1', '.']
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/gcp-project/quickstart-image:tag1'
options:
  logging: 'CLOUD_LOGGING_ONLY'